language: java

script: "mvn cobertura:cobertura"
  
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -Dgpg.skip=true -B -V

after_success:
  - bash <(curl -s https://codecov.io/bash)

jdk:
  - oraclejdk8
